#!/bin/bash

set -e

cd "$(dirname "$0")/../.."

echo "===> Installing changelog generator..."

if ! [ -x "$(command -v gem)" ]; then
  echo 'Error: gem is not installed'
  exit 1
fi

gem install github_changelog_generator