#!/bin/bash

cd "$(dirname "$0")/../.."

echo "===> Installing changelog generator..."

if ! [ -x "$(command -v gem)" ]; then
  echo 'Error: gem is not installed'
  exit 1
fi

sudo ~/ruby/bin/gem install github_changelog_generator