#!/bin/bash

cd "$(dirname "$0")/../.."

echo "===> Installing ruby..."

RUBY_FOLDER_NAME="ruby-2.5.0"

wget -O ${HOME}/${RUBY_FOLDER_NAME}.tar.gz http://ftp.ruby-lang.org/pub/ruby/2.5/${RUBY_FOLDER_NAME}.tar.gz
tar -xzvf $HOME/${RUBY_FOLDER_NAME}.tar.gz -C $HOME
rm $HOME/${RUBY_FOLDER_NAME}.tar.gz

cd $HOME/${RUBY_FOLDER_NAME}

./configure
make
sudo make install