#!/bin/sh

cd "$(dirname "$0")/.."
export $(egrep -v '^#' .env | xargs)

APP_VERSION=$(node -e 'console.log(require("./package.json").version)')

echo "===> Running Chandler..."

chandler push v${APP_VERSION}