#!/bin/sh

cd "$(dirname "$0")/.."

APP_NAME=$(node -e 'console.log(require("./package.json").name)')

echo "===> Running changelog generator..."
. ./.env

if ! [ -x "$(command -v github_changelog_generator)" ]; then
  echo 'Error: github_changelog_generator is not installed' >&2
  exit 1
fi

github_changelog_generator -u pedroarapua -p ${APP_NAME} --enhancement-labels 'enhancement,Enhancement,features,Features,feature' --exclude-labels 'duplicate,question,invalid,wontfix,ignore,changelog ignore' --base CHANGELOG.md