#!/bin/sh

# script/deploy: Deploy app at teresa PaaS

set -e

cd "$(dirname "$0")/.."
export $(egrep -v '^#' .env | xargs)

APP_NAME=$(node -e 'console.log(require("./package.json").name)')
VERSION=$(node -e 'console.log(require("./package.json").version)')

echo "===> Building app..."

if ! [ -x "$(command -v teresa)" ]; then
    echo 'Error: teresa is not installed' >&2
    exit 1
fi

if [[ $1 != "" ]]; then
    APP_NAME=$( echo $1)
fi

echo "===> Deploy..."

teresa deploy create . --app $APP_NAME --description "Deploy release $VERSION"