#!/bin/sh

# script/migration: Execute the migration script to update or downgrade database.

set -e

cd "$(dirname "$0")/.."
export $(egrep -v '^#' .env | xargs)

echo "===> Migrating DB..."
# node_modules/.bin/knex migrate:latest

echo "==> App is now ready to go!"