#!/bin/sh

cd "$(dirname "$0")/.."

APP_NAME=$(node -e 'console.log(require("./package.json").name)')

echo "===> Running Sonar..."

if [ -e "./.env" ]; then
  . ./.env
fi

sonar-scanner \
  -Dsonar.projectKey=${SONAR_APP_NAME:-${APP_NAME}} \
  -Dsonar.organization=${ORGANIZATION_NAME:-pedroarapua-github} \
  -Dsonar.sources=src \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=${SONAR_TOKEN}