#!/bin/sh

set -e

cd "$(dirname "$0")/.."
export $(egrep -v '^#' .env | xargs)

APP_NAME=$(node -e 'console.log(require("./package.json").name)')

echo "===> Running Sonar..."

if ! [ -x "$(command -v ~/sonar-scanner/bin/sonar-scanner)" ]; then
  echo 'Error: sonar-scanner is not installed'
  exit 1
fi

~/sonar-scanner/bin/sonar-scanner -Dsonar.analysis.mode=preview \
  -Dsonar.projectKey=${SONAR_APP_NAME:-${APP_NAME}} \
  -Dsonar.organization=${ORGANIZATION_NAME:-pedroarapua-github} \
  -Dsonar.github.pullRequest=${PULL_REQUEST_ID} \
  -Dsonar.github.repository=${ORGANIZATION_NAME:-pedroarapua-github}/${SONAR_APP_NAME:-${APP_NAME}} \
  -Dsonar.github.oauth=$GITHUB_ACCESS_TOKEN \
  -Dsonar.sources=src \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=${SONAR_TOKEN}