#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.


set -e

cd "$(dirname "$0")/.."
export $(egrep -v '^#' .env | xargs)

[ -z "$DEBUG" ] || set -x

echo "===> Running linter..."

node_modules/.bin/eslint .

export NODE_ENV="test"
scripts/setup

echo "===> Running tests..."

./node_modules/.bin/nyc --reporter=html --reporter=text ./node_modules/.bin/_mocha